create table if NOT EXISTS lord
(
    id   bigint generated by default as identity (start with 1),
    age  integer,
    name varchar(255),
    primary key (id)
);
create table if NOT EXISTS planets
(
    id      bigint generated by default as identity (start with 1),
    name    varchar(255),
    lord_id bigint,
    primary key (id)
);

alter table planets
    add constraint FKm27n8eo3jvhm9jslhxur2po5d foreign key (lord_id) references lord
