name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Jacoco report
        run: ./gradlew build jacocoTestReport
      - name: Build with Gradle
        run: ./gradlew build
      - uses: codecov/codecov-action@v1
        with:
          token: c30b0aea-60ed-45df-81e1-5e0c2485aa4b